In [1]:
import torch

In [2]:
import numpy as np
import matplotlib.pyplot as plt

# Initialization of tensors

In [3]:
x = torch.ones(3,2)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [4]:
x = torch.zeros(3,2)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [5]:
x = torch.rand(3,2)
x

tensor([[0.2394, 0.8867],
        [0.2341, 0.7080],
        [0.7589, 0.9212]])

In [6]:
x = torch.empty(3,2)
x

tensor([[0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [2.9642e+29, 1.0902e+27]])

In [7]:
x = torch.zeros_like(x)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [8]:
x = torch.linspace(3,2,10)
x

tensor([3.0000, 2.8889, 2.7778, 2.6667, 2.5556, 2.4444, 2.3333, 2.2222, 2.1111,
        2.0000])

In [9]:
x = torch.tensor(x)
x

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


tensor([3.0000, 2.8889, 2.7778, 2.6667, 2.5556, 2.4444, 2.3333, 2.2222, 2.1111,
        2.0000])

In [ ]:
x = torch.tensor([3.0000, 2.8889, 2.7778, 2.6667, 2.5556, 2.4444, 2.3333, 2.2222, 2.1111,
        2.0000])

In [ ]:
x

In [12]:
x.size()

torch.Size([10])

In [13]:
x[0:]

tensor([3.0000, 2.8889, 2.7778, 2.6667, 2.5556, 2.4444, 2.3333, 2.2222, 2.1111,
        2.0000])

In [14]:
x[5:]

tensor([2.4444, 2.3333, 2.2222, 2.1111, 2.0000])

In [15]:
x[2:8:3]

tensor([2.7778, 2.4444])

In [16]:
x=torch.rand(5,3)
y= x[1,1]
print(x,y)

tensor([[0.0609, 0.5252, 0.8340],
        [0.6047, 0.4216, 0.5790],
        [0.9714, 0.7435, 0.9877],
        [0.9436, 0.8176, 0.1584],
        [0.1757, 0.2982, 0.3082]]) tensor(0.4216)


In [17]:
y.item()

0.42163002490997314

In [18]:
y=x.view(3,5)
y

tensor([[0.0609, 0.5252, 0.8340, 0.6047, 0.4216],
        [0.5790, 0.9714, 0.7435, 0.9877, 0.9436],
        [0.8176, 0.1584, 0.1757, 0.2982, 0.3082]])

In [19]:
y=x.view(5,3,1)
y.shape

torch.Size([5, 3, 1])

# Sample Tensor Operations

In [20]:
x = torch.ones(3,2)
y = torch.ones(3,2)
z=x+y
print(z)
z=x-y
print(z)
z=x*y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [21]:
z=y.add(x)
z

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [22]:
z=y.sub(x)
z

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [23]:
z=y.add_(x)
z

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

# Numpy vs pytorch speed comparison

In [24]:
x_np=x.numpy()
print(type(x),type(x_np))
print(x_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [25]:
a=np.random.randn(5)
a

array([ 0.08658256, -0.68735635, -3.45501497,  0.15060451, -1.07937836])

In [26]:
a_torch=torch.from_numpy(a)
a_torch

tensor([ 0.0866, -0.6874, -3.4550,  0.1506, -1.0794], dtype=torch.float64)

In [27]:
print(type(a),type(a_torch))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [28]:
np.add(a,1,out=a)
print(a,a_torch)

[ 1.08658256  0.31264365 -2.45501497  1.15060451 -0.07937836] tensor([ 1.0866,  0.3126, -2.4550,  1.1506, -0.0794], dtype=torch.float64)


In [29]:
%%time
for i in range(1000):
    a=np.random.randn(1000,100)
    b=np.random.randn(100,1000)
    c=np.matmul(a,b)

Wall time: 15.9 s


In [30]:
%%time
for i in range(1000):
    a=torch.randn(1000,100)
    b=torch.randn(100,1000)
    c=torch.matmul(a,b)

Wall time: 7.65 s


In [31]:
%%time
for i in range(10):
    a=np.random.randn(10000,10000)
    b=np.random.randn(10000,10000)
    c=np.matmul(a,b)

Wall time: 7min 38s


In [32]:
%%time
for i in range(10):
    a=torch.randn(10000,10000)
    b=torch.randn(10000,10000)
    c=torch.matmul(a,b)

Wall time: 2min 58s


In [33]:
print(torch.cuda.device_count())

0


In [34]:
print(torch.cuda.device(0))
#print(torch.cuda.get_device_name(0))

In [35]:
cuda0 = torch.device('cuda:0')

In [36]:
a = torch.ones(3, 2, device=cuda0)
b = torch.ones(3, 2, device=cuda0)
c = a + b
print(c)

AssertionError: Torch not compiled with CUDA enabled

# Here my laptop has amd graphics prcessor so it is not cuda enabled

# Autodiff

In [37]:
x = torch.ones(5,3,requires_grad=True)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [38]:
y = x + 5

In [39]:
y

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)

In [40]:
z = y/2 +1
z

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]], grad_fn=<AddBackward0>)

In [41]:
t = torch.sum(y)
t

tensor(90., grad_fn=<SumBackward0>)

In [42]:
t.backward()

In [43]:
t

tensor(90., grad_fn=<SumBackward0>)

In [44]:
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [45]:
y.grad

C:\ProgramData\Anaconda3\lib\site-packages\torch\tensor.py:746: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "


In [46]:
x.grad

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [47]:
x = torch.ones(5,3,requires_grad=True)
y = x+5
print(y)
z = 1/(1+torch.exp(-y))
print(z)
s=torch.sum(z)
s.backward()
print(x.grad)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)
tensor([[0.9975, 0.9975, 0.9975],
        [0.9975, 0.9975, 0.9975],
        [0.9975, 0.9975, 0.9975],
        [0.9975, 0.9975, 0.9975],
        [0.9975, 0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025, 0.0025],
        [0.0025, 0.0025, 0.0025],
        [0.0025, 0.0025, 0.0025],
        [0.0025, 0.0025, 0.0025],
        [0.0025, 0.0025, 0.0025]])


# MP neuron autodiff sample by pytorch

In [48]:
lr = 0.01

w = torch.tensor(1.,requires_grad=True)
b = torch.tensor(1.,requires_grad=True)

print(w,b)

for i in range(10):
    x = torch.randn(20,1)
    y=3*x - 2
    y_hat = w * x + b
    loss = torch.sum((y_hat-y)**2)
    loss.backward()
    
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
        
        w.grad.zero_()
        b.grad.zero_()
        
    print(w.item(),b.item())

tensor(1., requires_grad=True) tensor(1., requires_grad=True)
1.5677493810653687 -0.1420344114303589
2.0450427532196045 -0.7419454455375671
2.5659992694854736 -1.2488903999328613
2.6085901260375977 -1.49900221824646
2.766441583633423 -1.6617586612701416
2.9200189113616943 -1.8319108486175537
2.9868619441986084 -1.9120985269546509
2.986356019973755 -1.946565866470337
2.9921658039093018 -1.9684572219848633
2.9960947036743164 -1.9814121723175049


# Do it for a large problem

In [58]:
%%time
lr = 0.01
epoch=200
N=1000000
w = torch.randn([N],requires_grad=True)
b = torch.ones([1],requires_grad=True)

#print(w,b)

for i in range(epoch):
    x = torch.randn([N])
    y=torch.dot(3*torch.ones([N]),x) - 2
    y_hat = torch.dot(w,x) + b
    loss = torch.sum((y_hat-y)**2)
    loss.backward()
    
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
        
        w.grad.zero_()
        b.grad.zero_()
        
    #print(w.item(),b.item())

Wall time: 5.9 s
